name: Python Ruff

on: [push, pull_request]

jobs:
  lint:
    name: Python Lint
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v1
      - name: Setup checkout
        uses: actions/checkout@master
      - name: Lint with ruff
        run: |
          pip install ruff
          ruff check volara tests
